# Generated by Django 4.1.7 on 2023-03-26 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="meal",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="core.meal"
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="food_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.foodtype",
            ),
        ),
        migrations.AlterField(
            model_name="recipeproduct",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.product",
            ),
        ),
    ]
