# Generated by Django 4.1.7 on 2023-03-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_diary_meal_alter_food_food_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="drained_grams",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="net_grams",
            field=models.FloatField(null=True),
        ),
    ]
