# Generated by Django 4.1.7 on 2023-03-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_product_drained_grams_alter_product_net_grams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="drained_grams",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="net_grams",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.productbrand",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.productcategory",
            ),
        ),
    ]
