# Generated by Django 4.1.7 on 2023-03-30 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_product_drained_grams_alter_product_net_grams_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeproduct",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="core.recipe",
            ),
        ),
    ]
