# Generated by Django 4.1.7 on 2023-04-04 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_recipeproduct_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="food",
            field=models.ForeignKey(
                default=22, on_delete=django.db.models.deletion.PROTECT, to="core.food"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="diary",
            name="meal",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="core.meal"
            ),
            preserve_default=False,
        ),
    ]
