# Generated by Django 4.1.7 on 2023-03-22 17:48

import authentication.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                default=authentication.models.Roles["USER"],
                on_delete=django.db.models.deletion.PROTECT,
                to="authentication.role",
            ),
        ),
    ]
